version: "3.8"

services:
  package-dev:
    image: project:package-dev-amd64
    build:
      context: ../..
      dockerfile: package/docker/dev.Dockerfile
    command: ["cargo", "test", "--manifest-path", "src/package/Cargo.toml"]

  package-prod:
    image: project:package-prod-amd64
    build:
      dockerfile: prod.Dockerfile
    command: [ "ros2" , "run", "package", "node" ]
    depends_on:
      - package-dev